name:  multistage pipeline

on:
  workflow_dispatch:

stages:
- stage: stage1
  displayname: first stage
  jobs:
  - job1:
      runs-on: ubuntu-latest
      steps:
        - run: |
            echo 'hi from stage 1 job1'

  - job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - run: |
            echo 'hello from stage1 job2'
