name: multi stage pipeline

on:
  workflow_dispatch:

jobs:
  stage1:
    runs-on: ubuntu-latest
    environment: stage1
    steps:
      - run: |
          echo 'hi from stage 1'

  stage2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'hello from stage2'
  
